"""initial_schema

Revision ID: 5e62426e4d2f
Revises: 
Create Date: 2026-05-30 23:42:43.180076
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5e62426e4d2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_url',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=True),
    sa.Column('portal_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.String(length=50), nullable=True),
    sa.Column('last_error_msg', sa.String(length=500), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_by', sa.String(length=100), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash', name='uq_article_url_hash'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_article_url_claim', 'article_url', ['status', 'next_retry_at', 'priority'], unique=False)
    op.create_index('ix_article_url_host', 'article_url', ['host'], unique=False)
    op.create_index('ix_article_url_keyword', 'article_url', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_article_url_status'), 'article_url', ['status'], unique=False)
    op.create_table('t_domain',
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('rules_json', sa.JSON(), nullable=True),
    sa.Column('rules_enabled', sa.Boolean(), nullable=False),
    sa.Column('rules_version', sa.Integer(), nullable=False),
    sa.Column('crawl_delay_ms', sa.Integer(), nullable=True),
    sa.Column('render_mode', sa.String(length=20), nullable=True),
    sa.Column('proxy_tier', sa.String(length=50), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.Column('recent_fail_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('avg_body_len', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('host'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('keyword',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('portal_type', sa.String(length=20), nullable=False, comment='NAVER|DAUM|GOOGLE|WEIBO'),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('last_discovered_at', sa.DateTime(), nullable=True),
    sa.Column('next_discover_at', sa.DateTime(), nullable=True),
    sa.Column('last_cursor', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword', 'portal_type', name='uq_keyword_portal'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_keyword_next_discover_at'), 'keyword', ['next_discover_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keyword_next_discover_at'), table_name='keyword')
    op.drop_table('keyword')
    op.drop_table('t_domain')
    op.drop_index(op.f('ix_article_url_status'), table_name='article_url')
    op.drop_index('ix_article_url_keyword', table_name='article_url')
    op.drop_index('ix_article_url_host', table_name='article_url')
    op.drop_index('ix_article_url_claim', table_name='article_url')
    op.drop_table('article_url')
    # ### end Alembic commands ###
